
#---- MODEL PARAMETERS
MODEL_PARAM: # input in the same order as class initialization
  BATCH_SIZE: 540
  TIME_FRAMES: 10
  KEYPOINTS: 17
  CHANNEL_IN: 3
  HEADS: 8
  LAYERS: 2
  LAST_MLP: 512
  CLASSES: 8

#---- MODEL CONFIG
DS_PATH: '../tools/datasets/labeled_datasets/'
TB_PATH: '../tools/logs/'
TB_COMMENT: '_our_ds'
MODEL_OUT_PATH: '../weights/model.pth'

#---- TRAINING PARAMETERS
TRAIN_PARAM:
  LEARNING_RATE: .00025
  WEIGHT_DECAY: .0001
  EPOCHS: 1200

